x-app-template: &app-template
  build:
    context: .
  env_file: .env
  volumes:
    - ${DATA_VOLUME}:/app/data
  stdin_open: true
  tty: true
  environment:
    - UV_PROJECT_ENVIRONMENT=/app/.venv
    

services:
  app:
    <<: *app-template
    profiles: ["cpu"]

  app-gpu:
    <<: *app-template
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    