x-app-template: &app-template
  build:
    context: .
    args:
      - PYTHON_VERSION=${PYTHON_VERSION}
  env_file: .env
  volumes:
    - ./src:/app/src
    - ./data:/app/data
    - ./config.yaml:/app/config.yaml
  stdin_open: true
  tty: true

services:
  app:
    <<: *app-template
    profiles: ["cpu"]

  app-gpu:
    <<: *app-template
    profiles: ["gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
  app-mps:
    <<: *app-template
    profiles: ["mps"]
    # Sadly, it doesnt work ...
    